;;-*-coding: utf-8;-*-
(define-abbrev-table 'global-abbrev-table
  '(
    ("addlayout" "addLayout" nil :count 8 :case-fixed t)
    ("addwidget" "addWidget" nil :count 20 :case-fixed t)
    ("currentindexchanged" "currentIndexChanged" nil :count 1 :case-fixed t)
    ("currenttextchanged" "currentTextChanged" nil :count 0 :case-fixed t)
    ("itemclicked" "itemClicked" nil :count 0 :case-fixed t)
    ("mapwidget" "MapWidget" nil :count 1 :case-fixed t)
    ("pg" "peut-gerer" nil :count 5 :case-fixed t)
    ("pp" "peut-publier" nil :count 2 :case-fixed t)
    ("precisetimer" "PreciseTimer" nil :count 0 :case-fixed t)
    ("qfiledialog" "QFileDialog" nil :count 5 :case-fixed t)
    ("qframe" "QFrame" nil :count 7 :case-fixed t)
    ("qhboxlayout" "QHBoxLayout" nil :count 7 :case-fixed t)
    ("qicon" "QIcon" nil :count 5 :case-fixed t)
    ("qlabel" "QLabel" nil :count 4 :case-fixed t)
    ("qmainwindow" "QMainWindow" nil :count 2 :case-fixed t)
    ("qobject" "QObject" nil :count 6 :case-fixed t)
    ("qpixmap" "QPixmap" nil :count 1 :case-fixed t)
    ("qplaintextedit" "QPlainTextEdit" nil :count 1 :case-fixed t)
    ("qpushbutton" "QPushButton" nil :count 1 :case-fixed t)
    ("qsplitter" "QSplitter" nil :count 2 :case-fixed t)
    ("qt" "Qt" nil :count 4 :case-fixed t)
    ("qtcore" "QtCore" nil :count 37 :case-fixed t)
    ("qtgui" "QtGui" nil :count 16 :case-fixed t)
    ("qtimer" "QTimer" nil :count 1 :case-fixed t)
    ("qttexttospeech" "QtTextToSpeech" nil :count 7 :case-fixed t)
    ("qtwidgets" "QtWidgets" nil :count 80 :case-fixed t)
    ("qvboxlayout" "QVBoxLayout" nil :count 12 :case-fixed t)
    ("qvoice" "QVoice" nil :count 1 :case-fixed t)
    ("qwebengineview" "QWebEngineView" nil :count 5 :case-fixed t)
    ("qwidget" "QWidget" nil :count 11 :case-fixed t)
    ("setcontentsmargins" "setContentsMargins" nil :count 0 :case-fixed t)
    ("setenabled" "setEnabled" nil :count 2 :case-fixed t)
    ("setframestyle" "setFrameStyle" nil :count 1 :case-fixed t)
    ("sethandlewidth" "setHandleWidth" nil :count 2 :case-fixed t)
    ("setlayout" "setLayout" nil :count 2 :case-fixed t)
    ("setplaintext" "setPlainText" nil :count 1 :case-fixed t)
    ("setsinglestep" "setSingleStep" nil :count 1 :case-fixed t)
    ("settickinterval" "setTickInterval" nil :count 1 :case-fixed t)
    ("settimertype" "setTimerType" nil :count 2 :case-fixed t)
    ("statechanged" "stateChanged" nil :count 0 :case-fixed t)
    ("textchanged" "textChanged" nil :count 3 :case-fixed t)
    ("textedited" "textEdited" nil :count 20 :case-fixed t)
    ("toplaintext" "toPlainText" nil :count 9 :case-fixed t)
    ("valuechanged" "valueChanged" nil :count 3 :case-fixed t)
   ))

