;;-*-coding: utf-8;-*-
(define-abbrev-table 'global-abbrev-table
  '(
    ("addlayout" "addLayout" nil :case-fixed t :count 7)
    ("addwidget" "addWidget" nil :case-fixed t :count 16)
    ("currentindexchanged" "currentIndexChanged" nil :case-fixed t :count 1)
    ("mapwidget" "MapWidget" nil :case-fixed t :count 1)
    ("pg" "peut-gerer" nil :case-fixed t :count 5)
    ("pp" "peut-publier" nil :case-fixed t :count 1)
    ("precisetimer" "PreciseTimer" nil :case-fixed t :count 0)
    ("qfiledialog" "QFileDialog" nil :case-fixed t :count 5)
    ("qframe" "QFrame" nil :case-fixed t :count 7)
    ("qhboxlayout" "QHBoxLayout" nil :case-fixed t :count 6)
    ("qicon" "QIcon" nil :case-fixed t :count 1)
    ("qlabel" "QLabel" nil :case-fixed t :count 2)
    ("qmainwindow" "QMainWindow" nil :case-fixed t :count 2)
    ("qobject" "QObject" nil :case-fixed t :count 6)
    ("qplaintextedit" "QPlainTextEdit" nil :case-fixed t :count 1)
    ("qpushbutton" "QPushButton" nil :case-fixed t :count 1)
    ("qsplitter" "QSplitter" nil :case-fixed t :count 2)
    ("qt" "Qt" nil :case-fixed t :count 4)
    ("qtcore" "QtCore" nil :case-fixed t :count 30)
    ("qtgui" "QtGui" nil :case-fixed t :count 7)
    ("qtimer" "QTimer" nil :case-fixed t :count 1)
    ("qttexttospeech" "QtTextToSpeech" nil :case-fixed t :count 7)
    ("qtwidgets" "QtWidgets" nil :case-fixed t :count 67)
    ("qvboxlayout" "QVBoxLayout" nil :case-fixed t :count 8)
    ("qvoice" "QVoice" nil :case-fixed t :count 1)
    ("qwebengineview" "QWebEngineView" nil :case-fixed t :count 5)
    ("qwidget" "QWidget" nil :case-fixed t :count 4)
    ("setenabled" "setEnabled" nil :case-fixed t :count 2)
    ("setframestyle" "setFrameStyle" nil :case-fixed t :count 1)
    ("sethandlewidth" "setHandleWidth" nil :case-fixed t :count 2)
    ("setplaintext" "setPlainText" nil :case-fixed t :count 1)
    ("setsinglestep" "setSingleStep" nil :case-fixed t :count 1)
    ("settext" "setText" nil :case-fixed t :count 9)
    ("settickinterval" "setTickInterval" nil :case-fixed t :count 1)
    ("settimertype" "setTimerType" nil :case-fixed t :count 2)
    ("textchanged" "textChanged" nil :case-fixed t :count 3)
    ("textedited" "textEdited" nil :case-fixed t :count 20)
    ("toplaintext" "toPlainText" nil :case-fixed t :count 9)
    ("valuechanged" "valueChanged" nil :case-fixed t :count 3)
   ))
