;;-*-coding: utf-8;-*-
(define-abbrev-table 'global-abbrev-table
  '(
    ("addlayout" "addLayout" nil :count 7)
    ("addwidget" "addWidget" nil :count 16)
    ("currentindexchanged" "currentIndexChanged" nil :count 1)
    ("mapwidget" "MapWidget" nil :count 1)
    ("pg" "peut-gerer" nil :count 5)
    ("pp" "peut-publier" nil :count 1)
    ("precisetimer" "PreciseTimer" nil :count 0)
    ("qfiledialog" "QFileDialog" nil :count 3)
    ("qframe" "QFrame" nil :count 7)
    ("qhboxlayout" "QHBoxLayout" nil :count 6)
    ("qlabel" "QLabel" nil :count 2)
    ("qmainwindow" "QMainWindow" nil :count 2)
    ("qobject" "QObject" nil :count 6)
    ("qplaintextedit" "QPlainTextEdit" nil :count 1)
    ("qpushbutton" "QPushButton" nil :count 1)
    ("qsplitter" "QSplitter" nil :count 2)
    ("qt" "Qt" nil :count 1)
    ("qtcore" "QtCore" nil :count 25)
    ("qtgui" "QtGui" nil :count 3)
    ("qtimer" "QTimer" nil :count 1)
    ("qttexttospeech" "QtTextToSpeech" nil :count 7)
    ("qtwidgets" "QtWidgets" nil :count 63)
    ("qvboxlayout" "QVBoxLayout" nil :count 8)
    ("qvoice" "QVoice" nil :count 1)
    ("qwebengineview" "QWebEngineView" nil :count 5)
    ("qwidget" "QWidget" nil :count 4)
    ("setenabled" "setEnabled" nil :count 2)
    ("setframestyle" "setFrameStyle" nil :count 1)
    ("sethandlewidth" "setHandleWidth" nil :count 2)
    ("setplaintext" "setPlainText" nil :count 1)
    ("setsinglestep" "setSingleStep" nil :count 1)
    ("settext" "setText" nil :count 9)
    ("settickinterval" "setTickInterval" nil :count 1)
    ("settimertype" "setTimerType" nil :count 2)
    ("textchanged" "textChanged" nil :count 3)
    ("textedited" "textEdited" nil :count 20 :case-fixed t)
    ("toplaintext" "toPlainText" nil :count 9)
    ("valuechanged" "valueChanged" nil :count 3)
   ))
